### ISSUE TITLE
How to modify the value of one of the fields individually

### ISSUE THREAD

**Issue by higher75** [F-Secure/mqtt_fuzz#6]
The tool you wrote is very good. I am learning what you have. I don't understand a bit now. I know that I can use wireshark to grab messages, but how do I initiate mqtt messages? And I want to modify one of them individually How to modify the value of a field

**Comment by anttivs** [comment]
If you mean how to initiate MQTT messages so that one can sniff them, you'd need an MQTT server and an MQTT client that run the protocol between them. Unfortunately, the tool knows nothing of the MQTT protocol so it cannot be used to create MQTT messages "from scratch". Creating specific types of MQTT messages for fuzzing purposes is dependent on the features of the client and server, or alternatively, one can just craft these messages by hand.

Also note that as the tool just replays fuzz cases and does not know anything about MQTT as such, it doesn't recalculate MQTT headers to correspond to fuzzed payloads. If you want to fuzz the payload processing part of your system, for increased effectiveness, one would need to ensure the MQTT header itself is valid.

If you can build test versions of whatever you're fuzzing, it would potentially be even more effective to fuzz your payload processing directly, i.e., just inject fuzzed payloads locally to whatever processes them, without having to go through MQTT.

**Comment by higher75** [comment]
thanks
