### ISSUE TITLE
MQTT server lost (non-clean fashion, closed cleanly)

### ISSUE THREAD

**Issue by carlosjpr-collab** [F-Secure/mqtt_fuzz#9]
During our tests, we are seeing these logs. @anttivs  can you please tell us what these mean ?. Are these  bugs or information ? .

1- 1618495267:1cbfbd73-fb17-4951-945d-583b6b111f13:Sending valid publish-received
1618495267:1cbfbd73-fb17-4951-945d-583b6b111f13:Fuzzer -> Server: b'UAIAAQ=='
1618495267:Connection to MQTT server lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.]
1618495267:Reconnecting
1618495267:Stopped fuzz run to 0.0.0.0:1883

2- MQTT server lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

3. In the end of every test, we have this error:  Could not run the fuzzer. Check -validcases and -radamsa options. The error was: [Errno 11] write could not complete without blocking

**Comment by anttivs** [comment]
It has been a long time since I had a working setup for this so this is all speculation, but generally speaking, losing a connection during a fuzz test run is typical. If the connection is closed gracefully, that is what would be expected, and if it is due to a crash, congratulations, your fuzzing just paid off.

Unfortunately I cannot provide any help on the set-up and configuration problems. I have only tested this with Radamsa 0.4a as described in the README, so I'd suggest trying with that version or alternatively trying to debug the Radamsa run yourselves.

As much as I'd like to be of help, mqtt-fuzz is effectively abandonware.

**Comment by carlosjpr-collab** [comment]
Thanks, your responses are so helpful.
   For this log
`   Connection to MQTT server lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.`
   
We see only this log in the broker:
`     "Socket error on client myclientid, disconnecting" 
`  
so  the connection is closed gracefully i suppose ?
